DROP TABLE IF EXISTS `USER`;
CREATE TABLE `USER` (
    ID BIGINT AUTO_INCREMENT NOT NULL,
    ACCOUNT VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    EMAIL_VERIFIED BOOLEAN DEFAULT FALSE,
    STATUS SMALLINT NOT NULL,
    LAST_LOGIN_TIME TIMESTAMP NULL DEFAULT NULL,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT unique_account UNIQUE (ACCOUNT)
);

DROP TABLE IF EXISTS VERIFICATION_CODE;
CREATE TABLE VERIFICATION_CODE (
    ID BIGINT AUTO_INCREMENT NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    CODE VARCHAR(10) NOT NULL,
    EXPIRATION_TIME TIMESTAMP NOT NULL,
    VERIFIED BOOLEAN DEFAULT FALSE,
    CREATE_TIME TIMESTAMP NOT NULL,
    PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS idx_email ON VERIFICATION_CODE(EMAIL);
CREATE INDEX IF NOT EXISTS idx_code ON VERIFICATION_CODE(CODE);
CREATE INDEX IF NOT EXISTS idx_expiration ON VERIFICATION_CODE(EXPIRATION_TIME);

